site_name: Neural Net documentations

theme:
  name: readthedocs

plugins:
  - mkdocstrings
  - search

nav:
  - Neural net docs: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - explanation.md
