Create Table IF NOT EXISTS Neurons(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  neuron_id BIGINT,
  n_in INTEGER,
  layer_id BIGINT,
  created_at  DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  type VARCHAR(50) NOT NULL,
  FOREIGN KEY (layer_id) REFERENCES Layers(layer_id)
);

Create Table IF NOT EXISTS Layers(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  layer_id BIGINT,
  n_out INTEGER,
  created_at  DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  type VARCHAR(50) NOT NULL
);

Create Table IF NOT EXISTS Weights(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  weight_id INTEGER NOT NULL,
  neuron_id BIGINT NOT NULL,
  created_at  DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  value REAL ,
  FOREIGN KEY (neuron_id) REFERENCES Neurons(neuron_id)
);