site_name: Neural Network documentations

theme:
  name: readthedocs

plugins:
  - mkdocstrings
  - search

nav:
  - Neural net docs: index.md
  - How-To Guides: how-to-guides.md
  - Reference: reference.md
